version: '3.4'

services:
  web:
    build:
      context: ./SpaceshipCargoTransport/
    environment:
      - ConnectionString=Server=db;Database=SpaceshipCargoDb;User Id=sa;Password=P@ssword
    ports:
      - "5100:80"
    depends_on:
      - db
      
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=P@ssword
      - ACCEPT_EULA=Y
    ports:
      - "8001:5432"